# UrlConfiguration
url:
    host: localhost
    port: 8080
    username: admin
    password: admin

# UrlProperties
services:
    google:
        host: google.com
    micronaut:
        host: micronaut.io

# BuildingProperties
building:
    name: Burj Khalifa
    city: Dubai
    floors: 163